dataset: 'nuScenes10Hz'
version: 'v1.0-trainval'
#version: 'v1.0-mini'
agent_setting: 'single_agent'
input_representation: 'graphs'

#define: &t_h 1
define: &t_h 0.5
#define: &t_f 2
define: &t_f 3

define: &map_extent [-25, 25, -10, 40]

train_set_args:
  split: 'train'
  t_h: *t_h
  t_f: *t_f
  map_extent: *map_extent 
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15

val_set_args:
  split: 'train_val'
  t_h: *t_h
  t_f: *t_f
  map_extent: *map_extent 
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15

test_set_args:
  split: 'val'
  t_h: *t_h
  t_f: *t_f
  map_extent: *map_extent 
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15

batch_size: 32
num_workers: 24
verbosity: True
