# Dataset and dataloader parameters
dataset: 'VOD'
mode: "vod"
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'graphs'

#define: &t_h 1
define: &t_h 0.5
#define: &t_f 2
define: &t_f 3

train_set_args: &ds_args
  split: 'train'
  t_h: *t_h 
  t_f: *t_f
  map_extent: [ -25, 25, -10, 40 ]
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  #random_flips: True
  random_flips: False

val_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'test'
  random_flips: False

batch_size: 32
  #batch_size: 2 
num_workers: 8


# Encoder parameters
#encoder_type: 'pgp_encoder'
encoder_type: 'pgpvod_encoder'
encoder_args:
  target_agent_feat_size: 5
  #target_agent_feat_size: 9
  target_agent_emb_size: 16
  target_agent_enc_size: 32
  node_feat_size: 6
  node_emb_size: 16
  node_enc_size: 32
  nbr_feat_size: 5
  nbr_emb_size: 16
  nbr_enc_size: 32
  nbr_agent_types: 4 
  num_gat_layers: 2

# Aggregator parameters
aggregator_type: 'pgp'
aggregator_args:
  pre_train: False
  #pre_train: True
  target_agent_enc_size: 32
  node_enc_size: 32
  pi_h1_size: 32
  pi_h2_size: 32
  horizon: 15
  num_samples: 1000
  emb_size: 128
  num_heads: 32


# Decoder parameters
decoder_type: 'lvm'
decoder_args:
  num_samples: 1000
  #op_len: 12
  #op_len: 20
  op_len: 30
  hidden_size: 128
  encoding_size: 160
  agg_type: 'sample_specific'
  lv_dim: 5
  num_clusters: 10


# Optimizer parameters
optim_args:
  lr: 0.001
  #lr: 0.0001
  scheduler_step: 10
  #scheduler_step: 100000
  scheduler_gamma: 0.5
  #scheduler_gamma: 1.


losses: ['min_ade_k', 'pi_bc']
loss_weights: [1, 0.5]
loss_args:
  - k: 10
  - dummy: 0


tr_metrics: ['min_ade_k', 'min_fde_k','miss_rate_k', 'pi_bc']
tr_metric_args:
  - k: 10
  - k: 10
  - k: 10
    dist_thresh: 0.5
  - dummy: 0

val_metrics: ['min_ade_k','min_ade_k', 'min_fde_k','min_fde_k', 'miss_rate_k', 'miss_rate_k', 'pi_bc']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 0.5
  - k: 10
    dist_thresh: 0.5
  - dummy: 0


log_freq: 10 
